#ifndef MODELVIEWER_GLOBAL_H
#define MODELVIEWER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODELVIEWER_LIBRARY)
#  define MODELVIEWERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODELVIEWERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODELVIEWER_GLOBAL_H
